services:
  server:
    image: docker.io/gitea/gitea:${GITEA_VERSION:-1.23.1}
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${PG_PASSWORD:?must be set}
      - VIRTUAL_HOST=${VIRTUAL_HOST:?must be set}
      - VIRTUAL_PORT=3000
    restart: always
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:14
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=${PG_PASSWORD:?must be set}
      - POSTGRES_DB=gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data

networks:
  default:
    name: portainer
    external: true
